name: usconstitution
version: '2.0'
summary: Read the US Constitution from your Terminal!
description: |
  Keep yourself educated on the U.S. Constitution right from the terminal! 
  
    **Install the snap**

    sudo snap install usconstitution
    
    **Run it**
    
    With ascii - usconstitution
    
    Without ascii - usconstitution -p

license: MIT

base: core20
grade: stable 
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

apps:
  usconstitution:
    command: bin/usconstitution
    environment:
      LC_ALL: C.UTF-8

parts: 
  usconstitution:
    source: https://github.com/kz6fittycent/USConstitution
    source-type: git
    plugin: python

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
      
    build-packages:
      - python3
      
    stage-packages:
      - python3
