name: usconstitution
adopt-info: usconstitution
summary: Read the US Constitution from your Terminal!
description: |
  Keep yourself educated on the U.S. Constitution right from the terminal! 

license: MIT

# Attempt at core20 build

base: core20
grade: stable 
confinement: strict

apps:
  usconstitution:
    command: usr/bin/usconstitution
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
     
parts: 
  usconstitution:
    source: https://github.com/kz6fittycent/USConstitution
    source-type: git
    plugin: python
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
      
    build-packages:
      - python3
      
    stage-packages:
      - python3
